/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.example;

import static java.lang.Thread.sleep;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import javax.swing.*;

/**
 *
 * @author Alex y Raul
 */
public class Ventana extends javax.swing.JFrame {

    private ZonaDescanso zonaDescanso;
    private ZonaComun zonaComun;
    private Tunel[] arrayTunel = new Tunel[4];
    private ZonaRiesgo[] arrayZonaRiesgo = new ZonaRiesgo[4];
    private Comedor comedor = new Comedor();
    String[] idHumanos = new String[5];
    String[] idZombie = new String[5];
     private ExecutorService executor = Executors.newSingleThreadExecutor(); // Executor para manejar hilos

    /**
     * Creates new form NewJFrame
     */
    public Ventana() {
        setTitle("Apocalipsis Zombi");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        initComponents();
        crearSimulacionSegundoPlano();
    }


    private void iniciarSimulacion() {

        for (int i = 0; i < 4; i++) {
            arrayZonaRiesgo[i] = new ZonaRiesgo();
        }

        for (int i = 0; i < 4; i++) {
            arrayTunel[i] = new Tunel(i, arrayZonaRiesgo[i]);
        }

        zonaComun = new ZonaComun(arrayTunel);
        zonaDescanso = new ZonaDescanso();
        //creacion zombie
        idZombie[0] = "Z";
        for (int i = 1; i <= 4; i++) {
            idZombie[i] = "0";
        }
        new Zombie(idZombie, 0, arrayZonaRiesgo).start();

        //creacion humanos
        int contadorHumano = 1;

        for (int t = 0; t < 10; t++) {
            for (int k = 0; k < 10; k++) {
                for (int i = 0; i < 10; i++) {
                    for (int j = 0; j < 10; j++) {

                        String num = String.format("%04d", contadorHumano);
                        idHumanos[0] = "H";
                        idHumanos[1] = String.valueOf(num.charAt(0));
                        idHumanos[2] = String.valueOf(num.charAt(1));
                        idHumanos[3] = String.valueOf(num.charAt(2));
                        idHumanos[4] = String.valueOf(num.charAt(3));

                        System.out.println(idHumanos[0] + idHumanos[1] + idHumanos[2] + idHumanos[3] + idHumanos[4]);
                        new Humano(idHumanos.clone(), comedor, arrayTunel, zonaComun, zonaDescanso).start();
                        contadorHumano++;

                        try {
                            sleep(500 + (int) (1500 * Math.random()));
                        } catch (InterruptedException ie) {
                            System.out.println("Error creando humano");
                        }
                    }
                }
            }
        }
    }
    private void crearSimulacionSegundoPlano() {
        executor.submit(new Runnable() {
            @Override
            public void run() {
                // Llamar a la creación de zombies y humanos en segundo plano
                iniciarSimulacion();
            }
        });
    }


    public void actualizarHumanosDescansando() {

        jTextAreaHumanosDescanso.setText("");  // Limpiar el JTextArea
        for (Humano hu : zonaDescanso.getListaHumanosDescansando()) {
            jTextAreaHumanosDescanso.append(", "+hu.getIdHumanoStr());
        }
        jTextAreaHumanosDescanso.setCaretPosition(jTextAreaHumanosDescanso.getDocument().getLength());
    }
    
    public void actualizarHumanosComedor() {

        jTextAreaHumanosComedor.setText("");  // Limpiar el JTextArea
        for (Humano hu : comedor.getListaHumanosComedor()) {
            jTextAreaHumanosComedor.append(" "+hu.getIdHumanoStr());
        }
        jTextAreaHumanosComedor.setCaretPosition(jTextAreaHumanosComedor.getDocument().getLength());
    }
    
    public void actualizarComida(){
        jTextFieldNumComida.setText(comedor.getComida().toString());
    }
    
    public void actualizarHumanosZonaComun() {

        jTextAreaHumanosZonaComun.setText("");  // Limpiar el JTextArea
        for (Humano hu : zonaComun.getListaHumanosZonaComun()) {
            jTextAreaHumanosZonaComun.append(" "+hu.getIdHumanoStr());
        }
        jTextAreaHumanosZonaComun.setCaretPosition(jTextAreaHumanosZonaComun.getDocument().getLength());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelRefugio = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelDescanso = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaHumanosDescanso = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaHumanosComedor = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldNumComida = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaHumanosZonaComun = new javax.swing.JTextArea();
        jPanelTuneles = new javax.swing.JPanel();
        jPaneZonaRiesgo = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout());

        jPanelRefugio.setBackground(new java.awt.Color(153, 255, 255));
        jPanelRefugio.setPreferredSize(new java.awt.Dimension(200, 400));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REFUGIO");

        jPanelDescanso.setBackground(new java.awt.Color(102, 102, 102));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Descansando");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jTextAreaHumanosDescanso.setColumns(20);
        jTextAreaHumanosDescanso.setRows(5);
        jScrollPane1.setViewportView(jTextAreaHumanosDescanso);

        javax.swing.GroupLayout jPanelDescansoLayout = new javax.swing.GroupLayout(jPanelDescanso);
        jPanelDescanso.setLayout(jPanelDescansoLayout);
        jPanelDescansoLayout.setHorizontalGroup(
            jPanelDescansoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDescansoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDescansoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelDescansoLayout.setVerticalGroup(
            jPanelDescansoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDescansoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setForeground(new java.awt.Color(153, 255, 255));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Comedor");

        jTextAreaHumanosComedor.setColumns(20);
        jTextAreaHumanosComedor.setRows(5);
        jScrollPane2.setViewportView(jTextAreaHumanosComedor);

        jLabel4.setText("Comida");

        jTextFieldNumComida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNumComidaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextFieldNumComida, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 1, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNumComida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Zona común");

        jTextAreaHumanosZonaComun.setColumns(20);
        jTextAreaHumanosZonaComun.setRows(5);
        jScrollPane3.setViewportView(jTextAreaHumanosZonaComun);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelRefugioLayout = new javax.swing.GroupLayout(jPanelRefugio);
        jPanelRefugio.setLayout(jPanelRefugioLayout);
        jPanelRefugioLayout.setHorizontalGroup(
            jPanelRefugioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelRefugioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRefugioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelDescanso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelRefugioLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelRefugioLayout.setVerticalGroup(
            jPanelRefugioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRefugioLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanelDescanso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelRefugio);

        jPanelTuneles.setPreferredSize(new java.awt.Dimension(200, 400));

        javax.swing.GroupLayout jPanelTunelesLayout = new javax.swing.GroupLayout(jPanelTuneles);
        jPanelTuneles.setLayout(jPanelTunelesLayout);
        jPanelTunelesLayout.setHorizontalGroup(
            jPanelTunelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 223, Short.MAX_VALUE)
        );
        jPanelTunelesLayout.setVerticalGroup(
            jPanelTunelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelTuneles);

        javax.swing.GroupLayout jPaneZonaRiesgoLayout = new javax.swing.GroupLayout(jPaneZonaRiesgo);
        jPaneZonaRiesgo.setLayout(jPaneZonaRiesgoLayout);
        jPaneZonaRiesgoLayout.setHorizontalGroup(
            jPaneZonaRiesgoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 223, Short.MAX_VALUE)
        );
        jPaneZonaRiesgoLayout.setVerticalGroup(
            jPaneZonaRiesgoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 406, Short.MAX_VALUE)
        );

        getContentPane().add(jPaneZonaRiesgo);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNumComidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNumComidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNumComidaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */ 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
                
            }
            
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPaneZonaRiesgo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelDescanso;
    private javax.swing.JPanel jPanelRefugio;
    private javax.swing.JPanel jPanelTuneles;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextAreaHumanosComedor;
    private javax.swing.JTextArea jTextAreaHumanosDescanso;
    private javax.swing.JTextArea jTextAreaHumanosZonaComun;
    private javax.swing.JTextField jTextFieldNumComida;
    // End of variables declaration//GEN-END:variables

}
